import {beforeEach,describe,expect,it,vi} from 'vitest';import {render,screen,waitFor} from '@testing-library/react';import userEvent from '@testing-library/user-event';import {MemoryRouter} from 'react-router-dom';import BERegister from './BERegister';import * as contacts from '../../api/contactsBureauEtude';import * as addressApi from '../../api/addressAutocomplete';
vi.mock('../../api/contactsBureauEtude');vi.mock('../../api/addressAutocomplete');
const suggestion={label:'10 rue de la Géologie 75001 Paris',rue:'10 rue de la Géologie',codePostal:'75001',ville:'Paris',latitude:48.86,longitude:2.34,score:.98};
const renderPage=()=>render(<MemoryRouter><BERegister/></MemoryRouter>);async function fill(user:ReturnType<typeof userEvent.setup>){await user.type(screen.getByLabelText('Raison sociale *'),'GeoExpert');await user.type(screen.getByLabelText('Email professionnel *'),'contact@geo.fr');await user.type(screen.getByLabelText('Téléphone *'),'0123456789');await user.type(screen.getByLabelText('Votre message *'),'Nous souhaitons rejoindre le réseau.');}
async function select(user:ReturnType<typeof userEvent.setup>){vi.mocked(addressApi.searchAddressSuggestions).mockResolvedValue([suggestion]);await user.type(screen.getByLabelText("Adresse de l'entreprise *"),'10 rue');await user.click(await screen.findByText(suggestion.label));}
describe('BERegister contact form',()=>{beforeEach(()=>{vi.clearAllMocks();vi.mocked(contacts.submitContactBureauEtude).mockResolvedValue();});
it('ne demande ni mot de passe ni document',()=>{renderPage();expect(screen.getByLabelText('Votre message *')).toBeTruthy();expect(screen.queryByLabelText(/mot de passe/i)).toBeNull();expect(screen.queryByText(/documents justificatifs/i)).toBeNull();});
it('exige une adresse sélectionnée',async()=>{const u=userEvent.setup();renderPage();await fill(u);await u.click(screen.getByRole('button',{name:'Envoyer mon message'}));expect(await screen.findByRole('alert')).toHaveTextContent('sélectionner une adresse');expect(contacts.submitContactBureauEtude).not.toHaveBeenCalled();});
it('soumet les informations et affiche la confirmation',async()=>{const u=userEvent.setup();renderPage();await fill(u);await select(u);await u.click(screen.getByRole('button',{name:'Envoyer mon message'}));await waitFor(()=>expect(contacts.submitContactBureauEtude).toHaveBeenCalledWith(expect.objectContaining({raisonSociale:'GeoExpert',email:'contact@geo.fr',message:'Nous souhaitons rejoindre le réseau.',adresse:expect.objectContaining({ville:'Paris',latitude:48.86})})));expect(await screen.findByText('Merci pour votre message')).toBeTruthy();});
it('affiche une erreur neutre en cas d’échec',async()=>{vi.mocked(contacts.submitContactBureauEtude).mockRejectedValue(new Error('secret'));const u=userEvent.setup();renderPage();await fill(u);await select(u);await u.click(screen.getByRole('button',{name:'Envoyer mon message'}));expect(await screen.findByRole('alert')).toHaveTextContent("n'a pas pu être envoyée");});});
